### ISSUE TITLE
Install_options not working on newer versions of nsclient.

### ISSUE THREAD

**Issue by nurriz** [voxpupuli/puppet-nsclient#32]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet:Server: 2.6.0 , Client 4.8.1
- Ruby: 2.1.9p490
- Distribution: Windows Server 2012 R2
- Module version: 1.4.0

## How to reproduce (e.g Puppet code you use)
Called:
  class { 'nsclient':
  package_source_location => 'https://github.com/mickem/nscp/releases/download/0.5.0.62',
  package_name            => 'NSClient++ (x64)',
  package_source          => 'NSCP-0.5.0.62-x64.msi',
  }
## What are you seeing
Install fails as the Custom Properties applied to the install are failing. The package can't be installed with either of the properties INSTALLLOCATION or CONFIGURATION_TYPE. Also fails manually.
## What behaviour did you expect instead
Silent install. I get a popup from msiexec.
## Any additional information you'd like to impart
Tried version 4.3, 5.0 and 5.1 of nsclient. Neither of them worked.
It seems dangerous to assume the package contains the mentioned custom properties. I'll look into a PR to make them optional.

**Comment by derektamsen** [comment]
For reference this is the debug of the full command puppet is running:
```
Debug: Executing: 'msiexec.exe /qn /norestart /i c:\temp\NSCP-0.5.0.62-x64.msi "INSTALLLOCATION=C:\Program Files\NSClient++" "CONFIGURATION_TYPE=ini://C:\Program Files\NSClient++\nsclient.ini" /quiet'
```

**Comment by derektamsen** [comment]
It appears this is the result of quotes being in the wrong location. This command works:
```
msiexec.exe /qn /norestart /i c:\temp\NSCP-0.5.0.62-x64.msi INSTALLLOCATION="C:\Program Files\NSClient++" CONFIGURATION_TYPE="ini://C:\Program Files\NSClient++\nsclient.ini" /quiet
```
