### ISSUE TITLE
This plugin should not use mode 

### ISSUE THREAD

**Issue by hdep** [voxpupuli/puppet-nsclient#64]
Hi,

this module should not set 'mode' for nsclient.ini because this is not well managed by windows. For example, in my environment I use a provided template, puppet constantly try to set mode permission, but fails silently. To solve this we can just let default permission. Moreover currenlty mode is hardcoded so I don't get any chance to fix the issue quickly.

If we want more precise permissions, we need to use ACL mechanism : 

```
Info: Applying configuration version '1545637771'
Notice: /Stage[main]/Nsclient::Service/File[C:\Program Files\NSClient++\nsclient.ini]/mode: mode changed '0774' to '0664
'
Info: /Stage[main]/Nsclient::Service/File[C:\Program Files\NSClient++\nsclient.ini]: Scheduling refresh of Service[nscp]

Notice: /Stage[main]/Nsclient::Service/Service[nscp]: Triggered 'refresh' from 1 event
Notice: Applied catalog in 17.63 seconds
```

**Comment by bastelfreak** [comment]
as far as I know the mode option is pretty linux specific. I don't see any benefit from having it on windows.

**Comment by hdep** [comment]
I agree with you here is PR   #65
